name: CD

on:
  release:
    types:
      - created

jobs:
  linux_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Linux and Windows Cross Compilers
        run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32 mingw-w64

      - name: Install rustup targets
        run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

      - name: Build the executable
        env:
          HOST_CC: gcc
          CC_x86_64_unknown_linux_gnu: /usr/bin/x86_64-linux-gnu-gcc
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: /usr/bin/x86_64-linux-gnu-gcc
        run: cargo build --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu

      - name: Tar x86_64 binary
        run: tar -czvf tls-bench-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release tls-bench

      - name: Zip windows binary
        run: zip -j tls-bench-windows.zip target/x86_64-pc-windows-gnu/release/tls-bench.exe

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 tls-bench-gnu-linux-x86_64.tar.gz > tls-bench-gnu-linux-x86_64.tar.gz.sha256
          shasum -a 256 tls-bench-windows.zip > tls-bench-windows.zip.sha256

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["tls-bench-gnu-linux-x86_64.tar.gz", "tls-bench-windows.zip", "tls-bench-gnu-linux-x86_64.tar.gz.sha256", "tls-bench-windows.zip.sha256"]'

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install rustup targets
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Build the executable
        run: cargo build --release --target=x86_64-apple-darwin --target=aarch64-apple-darwin

      - name: Zip x86_64 binary
        run: tar -czvf tls-bench-macos-x86_64.tar.gz -C target/x86_64-apple-darwin/release tls-bench

      - name: Zip arm64 binary
        run: tar -czvf tls-bench-macos-aarch64.tar.gz -C target/aarch64-apple-darwin/release tls-bench

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 tls-bench-macos-x86_64.tar.gz > tls-bench-macos-x86_64.tar.gz.sha256
          shasum -a 256 tls-bench-macos-aarch64.tar.gz > tls-bench-macos-aarch64.tar.gz.sha256

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["tls-bench-macos-x86_64.tar.gz", "tls-bench-macos-aarch64.tar.gz", "tls-bench-macos-x86_64.tar.gz.sha256", "tls-bench-macos-aarch64.tar.gz.sha256"]'
