name: CD

on:
  release:
    types:
      - created

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install rustup targets
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build the executable
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Tar x86_64 binary
        run: tar -czvf tls-bench-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release tls-bench

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 tls-bench-gnu-linux-x86_64.tar.gz > tls-bench-gnu-linux-x86_64.tar.gz.sha256

      - name: Upload assets
        uses: alexellis/upload-assets@0.4.1
        with:
          asset_paths: |
            tls-bench-gnu-linux-x86_64.tar.g
            tls-bench-gnu-linux-x86_64.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install rustup targets
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Build the executable
        run: cargo build --release --target=x86_64-apple-darwin --target=aarch64-apple-darwin

      - name: Zip x86_64 binary
        run: tar -czvf tls-bench-macos-x86_64.tar.gz -C target/x86_64-apple-darwin/release tls-bench

      - name: Zip arm64 binary
        run: tar -czvf tls-bench-macos-aarch64.tar.gz -C target/aarch64-apple-darwin/release tls-bench

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 tls-bench-macos-x86_64.tar.gz > tls-bench-macos-x86_64.tar.gz.sha256
          shasum -a 256 tls-bench-macos-aarch64.tar.gz > tls-bench-macos-aarch64.tar.gz.sha256

      - name: Upload assets
        uses: alexellis/upload-assets@0.4.1
        with:
          asset_paths: |
            tls-bench-macos-x86_64.tar.gz
            tls-bench-macos-aarch64.tar.gz
            tls-bench-macos-x86_64.tar.gz.sha256
            tls-bench-macos-aarch64.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
